apiVersion : apps/v1
kind: Deployment
metadata:
  name: simpleimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleimage
  template:
    metadata:
      labels:
        app: simpleimage 
    spec:
      containers:
        - name: simpleimage 
          image: tadarshtiwari1996.azurecr.io/simpleimage
          ports:
          - containerPort: 8080